services:
  notificaster:
    build:
      context: ./app/notificaster
      target: final
    environment:
      MONGODB_URI: "mongodb://notificaster:notificaster@mongodb:27017/notificaster"
      APP_PORT: "9001"
    ports:
      - "9001:9001"
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_APP_USER: notificaster
      MONGO_APP_PASS: notificaster
      MONGO_APP_DB: notificaster
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: echo 'db.runCommand({find:"notificaster"}).ok' | mongosh "mongodb://notificaster:notificaster@localhost:27017/notificaster" --quiet | grep -q 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
